### ISSUE TITLE
How to run the ruby script?

### ISSUE THREAD

**Issue by navaneet** [yoshimkd/swift-auto-diagram#11]
I also unable to run the command ruby generateEntityDiagram.rb.

When I run it the browser window opens in safari and simply sits there. There seems to be an error in the browser console 

<img width="1267" alt="error" src="https://user-images.githubusercontent.com/2356187/36471346-21823f76-1714-11e8-8ff0-de312cafcff8.png">

**Comment by ZdravkoN** [comment]
Hi @navaneet , can you try with Google Chrome?

**Comment by navaneet** [comment]
I can probably try to run it on firefox, I have it installed, don't have chrome right now. Can I change the browser that opens by default from the ruby script?

**Comment by yoshimkd** [comment]
@navaneet Just copy the URL of the generated file and paste it in another browser (preferably Chrome).

**Comment by navaneet** [comment]
K thanks
