### ISSUE TITLE
Problem zooming big diagram (no way to read it)

### ISSUE THREAD

**Issue by dsowsy** [yoshimkd/swift-auto-diagram#15]
I'm looking at a big project and there's no way to actually read what is being generated. 
In Chrome and Safari, I try to zoom with +/- keys and it just gets blurry, as in pictures attached.

I poked around the folder and saw that all of it is in diagram.js... Is this any known/standard format or could it be exported into some kind that I can see anything?

<img width="618" alt="entity" src="https://user-images.githubusercontent.com/978118/46156252-0fe60700-c247-11e8-8c73-588ee6cc78ac.png">
<img width="891" alt="zoomed" src="https://user-images.githubusercontent.com/978118/46156254-0fe60700-c247-11e8-9698-2201f91c37de.png">

**Comment by ZdravkoN** [comment]
Hi @dsowsy ,

I will look into it. Should be easy to enable it. Will get back to you.
