### ISSUE TITLE
why I'm not getting UML type of diagram

### ISSUE THREAD

**Issue by t2ac32** [yoshimkd/swift-auto-diagram#18]
I tried running on the whole project and even separate .swift files but I don't get uml diagrams just connection diagrams.

Am I doing something wrong??
![screen shot 2018-11-03 at 1 42 30 pm](https://user-images.githubusercontent.com/3275434/47952395-e9ff0100-df6e-11e8-960e-c63249e283c5.png)
![screen shot 2018-11-03 at 1 47 08 pm](https://user-images.githubusercontent.com/3275434/47952401-01d68500-df6f-11e8-8259-5837def5dc2b.png)

**Comment by yoshimkd** [comment]
Hello @t2ac32,

Thanks for reporting this issue, we weren't aware we introduced this in a recent merge. In an attempt to fix some loading performance issues, we unknowingly caused the properties and methods to disappear. As a workaround, you can use the version that shows the properties and methods: https://github.com/yoshimkd/swift-auto-diagram/tree/2b941966728c0c9919378d3786a4c60e7147c5d5.
We'll be trying to make a complete fix for the issues in the future.

Let us know whether the previous version works for you,
Best Regards,
Jovan

**Comment by crcdng** [comment]
Is the **Properties and methods are ignored** error going to be fixed? There seems to be some confusion with the closed issue #19, this issue, and issue #20. The original reported problem is still open - properties and methods are not shown.

**Comment by yoshimkd** [comment]
@i3games The properties and method are being shown again now. You can try with the `master` branch.

**Comment by crcdng** [comment]
Confirmed. Thank you for the update.

**Comment by t2ac32** [comment]
Confirmed as solved on master branch as of today. thanks!
