### ISSUE TITLE
Unsharp HTML

### ISSUE THREAD

**Issue by NF997** [yoshimkd/swift-auto-diagram#4]
First of all - I love the idea and really need this tool.
Maybe, I could contribute if you want so and I find the necessary time.
Unfortunately the HTML is completely unsharp when trying to get the diagram for my medium-large project.

**Comment by yoshimkd** [comment]
Hello @NF997. We're really happy you like the project and use it.
Of course the project is totally open to contributors so you can create a pull request.
If you want to talk more, you can write me an e-mail so we can schedule a meeting.

**Comment by NF997** [comment]
I will write you, as soon as I know that I actually have some time to work on this stuff.
