### ISSUE TITLE
IBOutlet

### ISSUE THREAD

**Issue by Shunwei** [yoshimkd/swift-auto-diagram#9]
Hi, first of all, thanks for the idea and this tool, really like it.
As I try to generate my class diagram, I noticed, if I have some IBOutlets in code, like:
`    @IBOutlet weak var tableview: UITableView!  \n
    @IBOutlet weak var imageView: UIImageView!
`
the result will be like this:
![bildschirmfoto 2017-10-19 um 15 20 13](https://user-images.githubusercontent.com/2315636/31773179-2fa0f23a-b4e2-11e7-9876-d54a8ef1810f.png)

Two instances with nothing will be generated as you can see, can you pls check it, if you have some time? many thanks!

**Comment by yoshimkd** [comment]
Hello Shunwei, I'm very happy you like this tool. You can check out the fixed version, this is the fix:
https://github.com/yoshimkd/swift-auto-diagram/commit/2b941966728c0c9919378d3786a4c60e7147c5d5

Thanks for noticing, cheers 👍

**Comment by Shunwei** [comment]
Great, thanks!
